#!/usr/bin/env python3
"""Generate custom_manifests/cluster-api-core.yaml from upstream Cluster API.

Vendors a CORE-ONLY, service-ca-webhook variant of cluster-api-components.yaml so
the CAPI core controller runs offline on OpenShift / air-gap:

  1. core-only      — drop the kubeadm bootstrap + control-plane providers
                      (we BYO bootstrap; only cluster/machine/MD/MS/MHC are needed).
  2. service-ca     — drop the cert-manager Certificate + Issuer; mark the webhook
                      Service with serving-cert-secret-name and every webhook
                      (admission + CRD conversion) with inject-cabundle, so OCP's
                      service-ca mints the cert (capi-webhook-service-cert) and
                      injects the CA bundle. (Same pattern as CAPA's 02-capa-webhooks.)
  3. no clusterctl  — resolve ${VAR:=default} substitutions to their defaults
                      (we `oc apply` directly, no clusterctl rendering).

Run on a host with GitHub access; commit the output. The core image is mirrored
separately by 04-prepare-mirror; the manifest is applied at the head of site-post.

Usage:  scripts/gen-cluster-api-core.py [CAPI_VERSION]    # default v1.12.7
"""
import re
import sys
import urllib.request
from collections import Counter

import yaml

VER = sys.argv[1] if len(sys.argv) > 1 else "v1.12.7"
URL = (
    "https://github.com/kubernetes-sigs/cluster-api/releases/download/"
    f"{VER}/cluster-api-components.yaml"
)
OUT = "custom_manifests/cluster-api-core.yaml"

text = urllib.request.urlopen(URL).read().decode()
# Resolve clusterctl-style ${VAR:=default} to the default (we apply directly).
text = re.sub(r"\$\{[A-Za-z0-9_]+:=([^}]*)\}", r"\1", text)

kept, dropped = [], Counter()
for d in yaml.safe_load_all(text):
    if not d:
        continue
    kind = d.get("kind", "")
    md = d.get("metadata", {}) or {}
    name = md.get("name", "")
    ns = md.get("namespace", "")
    # 1. drop the two kubeadm providers (namespaced + cluster-scoped + CRDs)
    if ns in ("capi-kubeadm-bootstrap-system", "capi-kubeadm-control-plane-system"):
        dropped["kubeadm"] += 1
        continue
    if "kubeadm" in name.lower():
        dropped["kubeadm"] += 1
        continue
    # 2. drop cert-manager; switch every inject-ca-from consumer to service-ca
    if kind in ("Certificate", "Issuer"):
        dropped["cert-manager"] += 1
        continue
    if kind == "Service" and name == "capi-webhook-service":
        md.setdefault("annotations", {})[
            "service.beta.openshift.io/serving-cert-secret-name"
        ] = "capi-webhook-service-cert"
    ann = md.get("annotations") or {}
    if "cert-manager.io/inject-ca-from" in ann:
        ann.pop("cert-manager.io/inject-ca-from")
        ann["service.beta.openshift.io/inject-cabundle"] = "true"
        md["annotations"] = ann
    # 3. OpenShift SCC: upstream pins the container's runAsUser/runAsGroup to 65532,
    #    which restricted-v2 rejects ("must be in ranges 100077xxxx" — the namespace
    #    UID range), so no pod is ever created (ReplicaFailure/FailedCreate). Drop
    #    them (keep runAsNonRoot / drop-ALL caps / seccompProfile, all SCC-compatible)
    #    and let OCP's SCC assign a compliant UID/GID.
    if kind == "Deployment":
        for c in (d.get("spec", {}).get("template", {}).get("spec", {}).get("containers") or []):
            csc = c.get("securityContext") or {}
            csc.pop("runAsUser", None)
            csc.pop("runAsGroup", None)
    kept.append(d)

header = (
    "# Cluster API CORE controller — vendored, core-only, service-ca webhooks (#62).\n"
    f"# GENERATED by scripts/gen-cluster-api-core.py from cluster-api {VER}.\n"
    "# DO NOT hand-edit — re-run the script to bump the version.\n"
    "# core-only (no kubeadm providers) + cert-manager→service-ca + clusterctl vars resolved.\n"
    "# Image registry.k8s.io/cluster-api/cluster-api-controller is mirrored by\n"
    "# 04-prepare-mirror; this manifest is applied at the head of site-post (before 08).\n"
)
with open(OUT, "w") as f:
    f.write(header)
    yaml.safe_dump_all(kept, f, default_flow_style=False, sort_keys=False)

print(f"wrote {OUT}: {len(kept)} docs kept, dropped {dict(dropped)}")
print(Counter(d.get("kind") for d in kept))
