#!/usr/bin/env python3
"""Write (and optionally commit) the provenance for a freshly baked RHCOS aliyun
boot image (P3-IMG.1). Stdlib-only.

Assembles bootimage/provenance/<rhcosVersion>.yaml — THE recipe + the observed
kargs baseline — so the supply chain has a durable, auditable record and detect
can skip already-baked versions. Run AFTER the offline gate passes.

  write_provenance.py --rhcos 9.6.x --ocp 4.20.22 --url <U> --sha256 <S> \
      --baseline /path/kargs.baseline --provenance-dir bootimage/provenance \
      [--guestfish 1.44.0] [--qemu-img 6.2.0] [--commit]

--commit: git add + commit + push (uses the checkout's credentials; pushes to
$GITHUB_REF_NAME or main). Without it, only the file is written (for testing).
"""
import argparse
import datetime
import os
import subprocess
import sys

SED = r"'s/ignition\.platform\.id=[a-z0-9]*/ignition.platform.id=aliyun/g'"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--rhcos", required=True)
    ap.add_argument("--ocp", required=True)
    ap.add_argument("--url", required=True)
    ap.add_argument("--sha256", required=True)
    ap.add_argument("--baseline", required=True, help="file with observed karg keys")
    ap.add_argument("--provenance-dir", required=True)
    ap.add_argument("--guestfish", default="unknown")
    ap.add_argument("--qemu-img", default="unknown")
    ap.add_argument("--commit", action="store_true")
    args = ap.parse_args(argv)

    baseline = [l.strip() for l in open(args.baseline) if l.strip()] \
        if os.path.exists(args.baseline) else []
    out = os.path.join(args.provenance_dir, f"{args.rhcos}.yaml")
    now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# Auto-generated by the bootimage supply chain (P3-IMG.1). THE recipe.",
        "schemaVersion: 1",
        f'ocpVersion: "{args.ocp}"',
        f'rhcosVersion: "{args.rhcos}"',
        "source:",
        "  format: openstack-qcow2.gz",
        f'  url: "{args.url}"',
        f'  sha256: "{args.sha256}"',
        "transform:",
        "  target: ignition.platform.id=aliyun",
        f"  sed: {SED}",
        '  files: ["/loader/entries/*.conf", "/grub2/grub.cfg"]',
        "tooling:",
        f'  guestfish: "{args.guestfish}"',
        f'  qemu-img: "{args.qemu_img}"',
        "  libguestfsBackend: direct",
        "kargsBaseline:",
        *[f"  - {k}" for k in baseline],
        "result:",
        "  gate: passed",
        "  bootSmoke: pending",
        f'  bakedAt: "{now}"',
        '  bakedBy: "github-actions/rhcos-aliyun-bootimage"',
    ]
    os.makedirs(args.provenance_dir, exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[provenance] wrote {out} ({len(baseline)} karg keys)")

    if not args.commit:
        return 0

    branch = os.environ.get("GITHUB_REF_NAME", "main")
    run = lambda *c, **k: subprocess.run(list(c), **k)
    run("git", "config", "user.name", "github-actions[bot]", check=True)
    run("git", "config", "user.email",
        "41898282+github-actions[bot]@users.noreply.github.com", check=True)
    run("git", "add", out, check=True)
    if run("git", "commit", "-m",
           f"chore(bootimage): provenance for RHCOS {args.rhcos} (OCP {args.ocp})").returncode != 0:
        print("[provenance] nothing to commit (already recorded)")
        return 0
    run("git", "pull", "--rebase", "--autostash", "origin", branch)  # best-effort
    run("git", "push", "origin", f"HEAD:{branch}", check=True)
    print(f"[provenance] pushed to {branch}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
